export interface CSSModel {
    id: number,
    class_name: '',
    description: '',
    imagepath: '',
    bgimage: '',
    image: '',
    width: Number,
    height: Number,
    font_color: '',
    font_size: Number,
    font_weight: Number,
    icon: '',
    bgcolor: '',
    text_align: '',
    padding_left: Number,
    padding_right: Number,
    padding_top: Number,
    padding_down: Number,
    margin_top: Number,
    margin_right: Number,
    margin_down: Number,
    margin_left: Number,
    justify_content: '',
    border: '',
    itemId: Number,
    lineHeight: Number
  };